# Generated by Django 4.2.5 on 2025-12-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0009_alter_conta_icone"),
        ("extrato", "0002_valores_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valores",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="perfil.categorias",
            ),
        ),
    ]
