# Generated by Django 4.2.5 on 2025-12-08 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("perfil", "0005_alter_conta_banco"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="perfis"),
                ),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cpf", models.CharField(blank=True, max_length=14, null=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("estado", models.CharField(blank=True, max_length=2, null=True)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
