# Generated by Django 4.2.5 on 2025-12-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0006_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_categoria",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="formato_data",
            field=models.CharField(
                blank=True, default="dd/mm/yyyy", max_length=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="idioma",
            field=models.CharField(
                blank=True, default="pt-BR", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="layout_dashboard",
            field=models.CharField(
                blank=True, default="comfortable", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="moeda",
            field=models.CharField(blank=True, default="BRL", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notificacoes_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tema",
            field=models.CharField(
                blank=True, default="system", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
