# Generated by Django 4.2.5 on 2025-12-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0008_categorias_user_conta_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="icone",
            field=models.ImageField(blank=True, null=True, upload_to="icones"),
        ),
    ]
